services:
  mysql:
    image: mysql:8.4.5
    container_name: mysql
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT:-3306}:${MYSQL_PORT:-3306}"
    expose:
      - ${MYSQL_PORT:-3306}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root1234}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user1234}
      MYSQL_CHARACTER_SET_SERVER: ${MYSQL_CHARACTER_SET:-utf8mb4}
      MYSQL_COLLATION_SERVER: ${MYSQL_COLLATION:-utf8mb4_unicode_ci}
      TZ: ${TZ:-Europe/Warsaw}
      MYSQL_TCP_PORT: ${MYSQL_PORT:-3306}
    volumes:
      - mysql_data:/var/lib/msql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root1234}"]
      timeout: 20s
      retries: 3
    networks:
      - mysql-network

volumes:
  mysql_data:

networks:
  mysql-network:
